# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/digi/Lab_09_10/Lab_09_10.cache/wt [current_project]
set_property parent.project_path D:/digi/Lab_09_10/Lab_09_10.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:basys3:part0:1.2 [current_project]
set_property ip_output_repo d:/digi/Lab_09_10/Lab_09_10.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  D:/digi/Lab_09_10/Lab_09_10.srcs/sources_1/new/Add_Sub_4bit.vhd
  D:/digi/Lab_09_10/Lab_09_10.srcs/sources_1/imports/new/Decoder_2_to_4.vhd
  D:/digi/Lab_09_10/Lab_09_10.srcs/sources_1/imports/new/Decoder_3_to_8.vhd
  D:/digi/Lab_09_10/Lab_09_10.srcs/sources_1/imports/new/FA.vhd
  D:/digi/Lab_09_10/Lab_09_10.srcs/sources_1/imports/new/HA.vhd
  D:/digi/Lab_09_10/Lab_09_10.srcs/sources_1/new/Instruction_Decoder.vhd
  D:/digi/Lab_09_10/Lab_09_10.srcs/sources_1/new/Instruction_Fetch.vhd
  D:/digi/Lab_09_10/Lab_09_10.srcs/sources_1/imports/new/LUT_16_7.vhd
  D:/digi/Lab_09_10/Lab_09_10.srcs/sources_1/imports/new/MUX_2_to_1_12.vhd
  D:/digi/Lab_09_10/Lab_09_10.srcs/sources_1/imports/lab9/MUX_2_to_1_3.vhd
  D:/digi/Lab_09_10/Lab_09_10.srcs/sources_1/imports/lab9/MUX_2_to_1_4.vhd
  D:/digi/Lab_09_10/Lab_09_10.srcs/sources_1/imports/lab9/MUX_8_to_1.vhd
  D:/digi/Lab_09_10/Lab_09_10.srcs/sources_1/imports/lab9/MUX_8_to_1_4.vhd
  D:/digi/Lab_09_10/Lab_09_10.srcs/sources_1/new/Nano_Processor.vhd
  D:/digi/Lab_09_10/Lab_09_10.srcs/sources_1/new/Out_controll_7seg.vhd
  D:/digi/Lab_09_10/Lab_09_10.srcs/sources_1/imports/lab9/ProgramROM.vhd
  D:/digi/Lab_09_10/Lab_09_10.srcs/sources_1/imports/new/ProgramROM_2.vhd
  D:/digi/Lab_09_10/Lab_09_10.srcs/sources_1/new/Program_Counter.vhd
  D:/digi/Lab_09_10/Lab_09_10.srcs/sources_1/imports/new/RCA_3.vhd
  D:/digi/Lab_09_10/Lab_09_10.srcs/sources_1/imports/lab9/RegisterBank.vhd
  D:/digi/Lab_09_10/Lab_09_10.srcs/sources_1/imports/lab9/Register_4bit.vhd
  D:/digi/Lab_09_10/Lab_09_10.srcs/sources_1/new/ResetController.vhd
  D:/digi/Lab_09_10/Lab_09_10.srcs/sources_1/imports/new/SlowClk_7seg.vhd
  D:/digi/Lab_09_10/Lab_09_10.srcs/sources_1/imports/new/Slow_Clk.vhd
  D:/digi/Lab_09_10/Lab_09_10.srcs/sources_1/new/Nano_Processor_with_7SegOut.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/digi/Lab_09_10/Lab_09_10.srcs/constrs_1/imports/Downloads/Basys3Labs.xdc
set_property used_in_implementation false [get_files D:/digi/Lab_09_10/Lab_09_10.srcs/constrs_1/imports/Downloads/Basys3Labs.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Nano_Processor_with_7SegOut -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Nano_Processor_with_7SegOut.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Nano_Processor_with_7SegOut_utilization_synth.rpt -pb Nano_Processor_with_7SegOut_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
